/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.worker.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ad8caf4ab170b406f4517246f37f014f)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	RAG_VECTORIZE: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
	JEV_CHAT_MODE: "shadow" | "off";
	ANTHROPIC_API_KEY: string;
	ADMIN_PASSWORD: string;
	VAPID_PRIVATE_KEY: string;
	VAPID_SUBJECT: string;
	TYPESAFE_API_KEY?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		VECTORIZE: VectorizeIndex;
		RAG_VECTORIZE: VectorizeIndex;
		AI: Ai;
		ASSETS: Fetcher;
		JEV_CHAT_MODE: "shadow";
		ANTHROPIC_API_KEY: string;
		ADMIN_PASSWORD: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_SUBJECT: string;
		TYPESAFE_API_KEY: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JEV_CHAT_MODE" | "ANTHROPIC_API_KEY" | "ADMIN_PASSWORD" | "VAPID_PRIVATE_KEY" | "VAPID_SUBJECT" | "TYPESAFE_API_KEY">> {}
}
