/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.worker.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: fb688e374f5de55aa0103cfe9cce44f8)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	RAG_VECTORIZE: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
	ANTHROPIC_API_KEY: string;
	ADMIN_PASSWORD: string;
	VAPID_PRIVATE_KEY: string;
	VAPID_SUBJECT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		VECTORIZE: VectorizeIndex;
		RAG_VECTORIZE: VectorizeIndex;
		AI: Ai;
		ASSETS: Fetcher;
		ANTHROPIC_API_KEY: string;
		ADMIN_PASSWORD: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_SUBJECT: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANTHROPIC_API_KEY" | "ADMIN_PASSWORD" | "VAPID_PRIVATE_KEY" | "VAPID_SUBJECT">> {}
}
