allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
approveBuilds: esbuild
overrides:
  "brace-expansion@1": "1.1.18"
  "brace-expansion@5": "5.0.9"
  "gray-matter>js-yaml": "3.15.1"
  "postcss": "8.5.23"
  "next>sharp": "0.35.2"
  "nanoid@3": "3.3.18"
patchedDependencies:
  '@opennextjs/cloudflare@1.20.6': patches/@opennextjs__cloudflare@1.20.6.patch
  gray-matter@4.0.3: patches/gray-matter@4.0.3.patch
