name = "sw-blog"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sw-blog-db"
database_id = "ccc1ea5a-cc5b-4507-b106-9b690908e540"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "sw-blog-media"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "blog-search"

[[vectorize]]
binding = "RAG_VECTORIZE"
index_name = "rag-chunks"
